import type { CountryCode } from "@/generated/prisma";

export const COUNTRIES: Record<CountryCode, { label: string }> = {
  af: { label: "Afghanistan" },
  al: { label: "Albania" },
  dz: { label: "Algeria" },
  ad: { label: "Andorra" },
  ch: { label: "Switzerland" },
  es: { label: "Spain" },
  fm: { label: "Micronesia" },
  gb: { label: "United Kingdom" },
  ao: { label: "Angola" },
  ag: { label: "Antigua and Barbuda" },
  ar: { label: "Argentina" },
  am: { label: "Armenia" },
  au: { label: "Australia" },
  at: { label: "Austria" },
  az: { label: "Azerbaijan" },
  ae: { label: "United Arab Emirates" },
  bs: { label: "Bahamas" },
  bh: { label: "Bahrain" },
  bd: { label: "Bangladesh" },
  bb: { label: "Barbados" },
  by: { label: "Belarus" },
  be: { label: "Belgium" },
  bz: { label: "Belize" },
  bj: { label: "Benin" },
  bt: { label: "Bhutan" },
  bo: { label: "Bolivia" },
  ba: { label: "Bosnia and Herzegovina" },
  bw: { label: "Botswana" },
  br: { label: "Brazil" },
  bn: { label: "Brunei" },
  bg: { label: "Bulgaria" },
  bf: { label: "Burkina Faso" },
  bi: { label: "Burundi" },
  cm: { label: "Cameroon" },
  ca: { label: "Canada" },
  cv: { label: "Cape Verde" },
  cf: { label: "Central African Republic" },
  cl: { label: "Chile" },
  cn: { label: "China" },
  co: { label: "Colombia" },
  km: { label: "Comoros" },
  cg: { label: "Republic of the Congo" },
  cd: { label: "Democratic Republic of the Congo" },
  cr: { label: "Costa Rica" },
  ci: { label: "Ivory Coast" },
  hr: { label: "Croatia" },
  cu: { label: "Cuba" },
  cy: { label: "Cyprus" },
  cz: { label: "Czech Republic" },
  dk: { label: "Denmark" },
  dj: { label: "Djibouti" },
  dm: { label: "Dominica" },
  do: { label: "Dominican Republic" },
  ec: { label: "Ecuador" },
  eg: { label: "Egypt" },
  er: { label: "Eritrea" },
  gq: { label: "Equatorial Guinea" },
  ee: { label: "Estonia" },
  et: { label: "Ethiopia" },
  fj: { label: "Fiji" },
  fi: { label: "Finland" },
  fr: { label: "France" },
  ga: { label: "Gabon" },
  gm: { label: "Gambia" },
  ge: { label: "Georgia" },
  de: { label: "Germany" },
  gh: { label: "Ghana" },
  gr: { label: "Greece" },
  gd: { label: "Grenada" },
  gt: { label: "Guatemala" },
  gn: { label: "Guinea" },
  gw: { label: "Guinea-Bissau" },
  gy: { label: "Guyana" },
  ht: { label: "Haiti" },
  hn: { label: "Honduras" },
  hu: { label: "Hungary" },
  is: { label: "Iceland" },
  in: { label: "India" },
  id: { label: "Indonesia" },
  ir: { label: "Iran" },
  iq: { label: "Iraq" },
  ie: { label: "Ireland" },
  il: { label: "Israel" },
  it: { label: "Italy" },
  jm: { label: "Jamaica" },
  jp: { label: "Japan" },
  jo: { label: "Jordan" },
  ke: { label: "Kenya" },
  kg: { label: "Kyrgyzstan" },
  kh: { label: "Cambodia" },
  ki: { label: "Kiribati" },
  kn: { label: "Saint Kitts and Nevis" },
  kp: { label: "North Korea" },
  kr: { label: "South Korea" },
  kw: { label: "Kuwait" },
  kz: { label: "Kazakhstan" },
  la: { label: "Laos" },
  lb: { label: "Lebanon" },
  lc: { label: "Saint Lucia" },
  li: { label: "Liechtenstein" },
  lk: { label: "Sri Lanka" },
  lr: { label: "Liberia" },
  ls: { label: "Lesotho" },
  lt: { label: "Lithuania" },
  lu: { label: "Luxembourg" },
  lv: { label: "Latvia" },
  ly: { label: "Libya" },
  ma: { label: "Morocco" },
  mc: { label: "Monaco" },
  md: { label: "Moldova" },
  me: { label: "Montenegro" },
  mg: { label: "Madagascar" },
  mh: { label: "Marshall Islands" },
  mk: { label: "North Macedonia" },
  ml: { label: "Mali" },
  mm: { label: "Myanmar" },
  mn: { label: "Mongolia" },
  mr: { label: "Mauritania" },
  mt: { label: "Malta" },
  mu: { label: "Mauritius" },
  mv: { label: "Maldives" },
  mw: { label: "Malawi" },
  mx: { label: "Mexico" },
  my: { label: "Malaysia" },
  mz: { label: "Mozambique" },
  na: { label: "Namibia" },
  ne: { label: "Niger" },
  ng: { label: "Nigeria" },
  ni: { label: "Nicaragua" },
  nl: { label: "Netherlands" },
  no: { label: "Norway" },
  np: { label: "Nepal" },
  nr: { label: "Nauru" },
  nz: { label: "New Zealand" },
  om: { label: "Oman" },
  pa: { label: "Panama" },
  pe: { label: "Peru" },
  pg: { label: "Papua New Guinea" },
  ph: { label: "Philippines" },
  pk: { label: "Pakistan" },
  pl: { label: "Poland" },
  pt: { label: "Portugal" },
  pw: { label: "Palau" },
  py: { label: "Paraguay" },
  qa: { label: "Qatar" },
  ro: { label: "Romania" },
  rs: { label: "Serbia" },
  ru: { label: "Russia" },
  rw: { label: "Rwanda" },
  sa: { label: "Saudi Arabia" },
  sb: { label: "Solomon Islands" },
  sc: { label: "Seychelles" },
  sd: { label: "Sudan" },
  se: { label: "Sweden" },
  sg: { label: "Singapore" },
  si: { label: "Slovenia" },
  sk: { label: "Slovakia" },
  sl: { label: "Sierra Leone" },
  sm: { label: "San Marino" },
  sn: { label: "Senegal" },
  so: { label: "Somalia" },
  sr: { label: "Suriname" },
  ss: { label: "South Sudan" },
  st: { label: "Sao Tome and Principe" },
  sv: { label: "El Salvador" },
  sy: { label: "Syria" },
  sz: { label: "Eswatini" },
  td: { label: "Chad" },
  tg: { label: "Togo" },
  th: { label: "Thailand" },
  tj: { label: "Tajikistan" },
  tl: { label: "Timor-Leste" },
  tm: { label: "Turkmenistan" },
  tn: { label: "Tunisia" },
  to: { label: "Tonga" },
  tr: { label: "Turkey" },
  tt: { label: "Trinidad and Tobago" },
  tv: { label: "Tuvalu" },
  tz: { label: "Tanzania" },
  ua: { label: "Ukraine" },
  ug: { label: "Uganda" },
  us: { label: "United States" },
  uy: { label: "Uruguay" },
  uz: { label: "Uzbekistan" },
  va: { label: "Vatican City" },
  vc: { label: "Saint Vincent and the Grenadines" },
  ve: { label: "Venezuela" },
  vn: { label: "Vietnam" },
  vu: { label: "Vanuatu" },
  ws: { label: "Samoa" },
  ye: { label: "Yemen" },
  za: { label: "South Africa" },
  zm: { label: "Zambia" },
  zw: { label: "Zimbabwe" },
} as const;
