import path from "path";

import { defineConfig } from "vitest/config";

const aliases = {
  "@": path.resolve(__dirname, "."),
  "@api": path.resolve(__dirname, "./app/api"),
  "server-only": path.resolve(__dirname, "./tests/helpers/server-only.ts"),
};
const testEnvironment = {
  APP_MODE: "self-hosted",
  BASE_URL: "http://localhost:4000",
  BETTER_AUTH_SECRET: "vitest-secret",
};
const domTestFiles = [
  "components/data-view/filter-palette/__tests__/use-filter-palette.dom.test.ts",
  "components/ui/__tests__/segmented-control.dom.test.tsx",
  "components/forms/__tests__/form-footer-actions.dom.test.ts",
  "components/modal/__tests__/confirm-dialog.dom.test.ts",
  "components/records/__tests__/record-operation-progress.dom.test.ts",
  "app/**/records/**/components/__tests__/use-record-deletion.dom.test.ts",
  "app/**/records/**/components/__tests__/record-import-dialog.dom.test.ts",
  "app/**/configure/components/__tests__/calculation-literal-input.dom.test.ts",
  "features/messaging/activities/__tests__/record-activities-panel.test.ts",
  "components/ai-elements/__tests__/message-links.test.ts",
  "app/[locale]/(public)/auth/reset-password/__tests__/reset-password-form.test.ts",
  "app/[locale]/(static)/contact/__tests__/contact-form.test.ts",
  "app/**/wiki/components/__tests__/wiki-page-view.test.ts",
  "app/**/wiki/components/__tests__/wiki-page-outline.test.ts",
  "app/**/wiki/components/__tests__/wiki-page-editor.test.ts",
  "app/**/wiki/components/__tests__/use-wiki-pages.test.ts",
  "app/**/dashboard/components/__tests__/widget-chart.test.ts",
  "app/**/dashboard/components/__tests__/record-widget-preview.dom.test.ts",
  "app/**/dashboard/components/__tests__/record-widget-chart-types.dom.test.ts",
  "app/**/dashboard/components/__tests__/widget-display-type-picker.dom.test.ts",
  "app/**/dashboard/components/__tests__/widget-chart-components.dom.test.ts",
  "app/[locale]/(protected)/__tests__/protected-layout.test.ts",
  "app/**/onboarding/wizard/components/__tests__/onboarding-wizard.test.ts",
  "app/components/agent-chat/__tests__/use-activity-group-state.test.ts",
  "app/components/agent-chat/__tests__/agent-chat-items.dom.test.ts",
  "app/components/agent-chat/__tests__/agent-composer-contexts.dom.test.ts",
  "app/components/agent-chat/__tests__/agent-composer-context-shortcut.dom.test.ts",
  "app/components/agent-chat/__tests__/agent-context-picker-focus.dom.test.ts",
  "app/components/agent-chat/__tests__/agent-route-reload.integration.test.ts",
  "app/components/agent-chat/__tests__/agent-saved-view-roundtrip.integration.test.ts",
  "app/components/agent-chat/__tests__/suggested-questions.test.ts",
  "app/components/agent-chat/__tests__/agent-chat-panel.test.ts",
  "app/components/agent-chat/__tests__/agent-tour-overlay-dialog.test.ts",
  "app/components/__tests__/shell-header.test.ts",
  "app/components/navigation/__tests__/navigation-switch.test.ts",
  "app/components/navigation/__tests__/public-navbar-menu.test.ts",
  "core/base/__tests__/data-view-autosave.test.ts",
  "core/base/__tests__/base-data-view-clear-grouping.test.ts",
  "core/base/__tests__/grouped-merge.test.ts",
  "core/base/__tests__/base-data-view-view-mode-race.test.ts",
  "core/base/__tests__/persist-view-options-rejection.test.ts",
  "core/utils/__tests__/server-rendered-client.dom.test.ts",
  "core/utils/__tests__/clipboard.test.ts",
  "core/utils/__tests__/background-poll.dom.test.ts",
  "core/utils/__tests__/use-is-truncated.test.ts",
  "components/data-view/__tests__/is-interactive-click.test.ts",
  "components/data-view/__tests__/data-table-grouping.test.tsx",
  "components/data-view/__tests__/data-kanban-order.test.tsx",
  "components/data-view/__tests__/board-drag-gating.test.tsx",
  "components/data-view/__tests__/group-summaries.test.tsx",
  "components/data-view/__tests__/board-grouping-prompt.test.tsx",
  "components/data-view/__tests__/data-view-url-sync.test.ts",
  "components/data-view/__tests__/data-view-views-rail-interaction.test.ts",
  "components/data-view/header/__tests__/view-menu-ai-interaction.test.ts",
  "components/data-view/__tests__/use-data-view-sync.test.ts",
  "components/data-view/filter-modal/inputs/__tests__/filter-input-number.test.ts",
  "components/data-view/filter-palette/__tests__/filter-palette-keyboard.test.tsx",
  "components/data-view/filter-palette/__tests__/filter-palette-pages.test.tsx",
  "components/entity-detail/__tests__/entity-detail-personalization.test.ts",
  "components/entity-detail/__tests__/entity-detail-summary.test.ts",
  "components/entity-detail/__tests__/entity-detail-visibility.test.tsx",
  "components/entity-detail/__tests__/entity-detail-panels.dom.test.ts",
  "components/marketing/__tests__/browser-frame.test.tsx",
  "components/marketing/__tests__/homepage-hero-sequence.test.tsx",
  "components/forms/__tests__/form-context.test.ts",
  "components/forms/__tests__/form-select-help.test.ts",
  "components/forms/__tests__/form-decimal-input.test.ts",
  "components/forms/__tests__/selection-command.test.ts",
  "components/editor/__tests__/email-markdown-editor.test.ts",
  "components/editor/__tests__/editor.dom.test.ts",
  "components/editor/__tests__/editor-menu.dom.test.ts",
  "app/[locale]/(protected)/records/[typeId]/components/__tests__/record-channels.dom.test.ts",
  "app/[locale]/(protected)/records/[typeId]/components/__tests__/record-detail-personalization.dom.test.ts",
  "app/[locale]/(protected)/records/[typeId]/components/__tests__/record-relationship-editor.dom.test.ts",
  "components/editor/__tests__/editor-link-picker.test.ts",
  "components/wiki/__tests__/wiki-homepage-setup.test.ts",
  "components/wiki/__tests__/wiki-refresh-safety.test.ts",
  "components/modal/__tests__/delete-confirmation-modal.test.ts",
  "components/modal/__tests__/navigation-history-guard.test.ts",
  "components/modal/__tests__/app-modal-assistant.test.ts",
  "components/modal/__tests__/responsive-overlay-assistant.test.ts",
  "components/acquisition/__tests__/public-ad-attribution-consent.test.ts",
  "components/scroll/__tests__/messages-scroll-container.test.ts",
  "components/shared/__tests__/overflow-rail.test.ts",
  "components/layout/__tests__/resizable-panels.test.ts",
  "components/shared/__tests__/use-p13n-column-widths.test.ts",
  "components/shared/__tests__/unexpected-error-toaster.test.ts",
  "core/stores/__tests__/root-store-provider.test.ts",
  "core/stores/__tests__/use-hydrated-intl-store.test.ts",
  "features/messaging/__tests__/message-presentation.test.ts",
  "app/[locale]/(protected)/settings/(account)/components/__tests__/account-signature-behavior.test.ts",
  "app/[locale]/(protected)/routines/components/__tests__/routine-modal.render.test.tsx",
  "app/[locale]/(protected)/routines/components/__tests__/routine-runs-pane.render.test.tsx",
  "features/messaging/__tests__/email-frame.test.ts",
  "app/[locale]/(protected)/inbox/components/__tests__/thread-reply-composer-navigation.test.ts",
  "app/[locale]/(protected)/inbox/components/__tests__/email-message-header.test.ts",
  "app/components/navigation/__tests__/use-marketing-account-state.test.ts",
  "components/ui/__tests__/tooltip.dom.test.ts",
  "components/keyboard/__tests__/key-matching-context.dom.test.ts",
  "app/components/keyboard-shortcuts/__tests__/global-keyboard-shortcuts.dom.test.ts",
  "components/ui/__tests__/overlay-focus-return.dom.test.ts",
];

export default defineConfig({
  test: {
    globals: true,
    maxWorkers: 4,
    environment: "node",
    include: ["**/__tests__/**/*.test.ts", "tests/conventions/*.test.ts"],
    exclude: ["node_modules", ".next", "generated"],
    projects: [
      {
        resolve: { alias: aliases },
        test: {
          name: "node",
          globals: true,
          environment: "node",
          env: testEnvironment,
          include: ["**/__tests__/**/*.test.ts", "tests/conventions/*.test.ts"],
          exclude: ["node_modules", ".next", "generated", ...domTestFiles],
          server: { deps: { inline: [/next-intl/] } },
        },
      },
      {
        resolve: { alias: aliases },
        test: {
          name: "dom",
          globals: true,
          environment: "jsdom",
          env: testEnvironment,
          server: { deps: { inline: [/next-intl/] } },
          include: domTestFiles,
          exclude: ["node_modules", ".next", "generated"],
        },
      },
    ],
    env: testEnvironment,
  },
  resolve: {
    alias: aliases,
  },
});
