const SYNTHETIC_AVATAR_DIRECTORY = "/demo/avatars/photos";

export const SYNTHETIC_CONTACT_AVATAR_PATHS = [
  `${SYNTHETIC_AVATAR_DIRECTORY}/leon-becker.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/tim-wagner.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/lucio-ball.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/mara-bauer.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/max-schmidt.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/sophie-hoffmann.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/jonas-weber.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/amin-hassan.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/lea-bauer.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/maxine-zoll.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/lina-alvarez.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/felix-koch.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/omar-khalil.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/tim-weber.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/kian-rahimi.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/leila-chen.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/mia-schneider.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/laura-fischer.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/amir-haddad.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/sophie-wagner.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/reinhold-mertens.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/alexej-sofr.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/anna-mueller.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/yasmin-farouk.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/lukas-fischer.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/felix-schneider.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/rashid-malik.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/paul-koch.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/nia-johnson.png`,
  `${SYNTHETIC_AVATAR_DIRECTORY}/paul-fischer.png`,
] as const;

export const SYNTHETIC_AVATAR_PATHS = {
  aminHassan: SYNTHETIC_CONTACT_AVATAR_PATHS[7],
  annaMueller: SYNTHETIC_CONTACT_AVATAR_PATHS[22],
  claraNeumann: `${SYNTHETIC_AVATAR_DIRECTORY}/clara-neumann.png`,
  elenaHoffmann: `${SYNTHETIC_AVATAR_DIRECTORY}/elena-hoffmann.png`,
  jonasWeber: SYNTHETIC_CONTACT_AVATAR_PATHS[6],
  leonBecker: SYNTHETIC_CONTACT_AVATAR_PATHS[0],
  marcoSilva: `${SYNTHETIC_AVATAR_DIRECTORY}/marco-silva.png`,
  maxBergmann: `${SYNTHETIC_AVATAR_DIRECTORY}/max-bergmann.png`,
  rashidMalik: SYNTHETIC_CONTACT_AVATAR_PATHS[26],
  sofiaRossi: `${SYNTHETIC_AVATAR_DIRECTORY}/sofia-rossi.png`,
  sophieWagner: SYNTHETIC_CONTACT_AVATAR_PATHS[19],
  yasminFarouk: SYNTHETIC_CONTACT_AVATAR_PATHS[23],
} as const;
