export const SYNTHETIC_AVATAR_ORIGIN = "https://customermates.com";

const SYNTHETIC_AVATAR_BASE_URL = `${SYNTHETIC_AVATAR_ORIGIN}/demo/avatars/photos`;

export const SYNTHETIC_CONTACT_AVATAR_URLS = [
  `${SYNTHETIC_AVATAR_BASE_URL}/leon-becker.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/tim-wagner.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/lucio-ball.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/mara-bauer.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/max-schmidt.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/sophie-hoffmann.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/jonas-weber.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/amin-hassan.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/lea-bauer.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/maxine-zoll.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/lina-alvarez.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/felix-koch.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/omar-khalil.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/tim-weber.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/kian-rahimi.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/leila-chen.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/mia-schneider.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/laura-fischer.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/amir-haddad.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/sophie-wagner.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/reinhold-mertens.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/alexej-sofr.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/anna-mueller.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/yasmin-farouk.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/lukas-fischer.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/felix-schneider.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/rashid-malik.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/paul-koch.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/nia-johnson.png`,
  `${SYNTHETIC_AVATAR_BASE_URL}/paul-fischer.png`,
] as const;

export const SYNTHETIC_AVATAR_URLS = {
  aminHassan: SYNTHETIC_CONTACT_AVATAR_URLS[7],
  annaMueller: SYNTHETIC_CONTACT_AVATAR_URLS[22],
  claraNeumann: `${SYNTHETIC_AVATAR_BASE_URL}/clara-neumann.png`,
  elenaHoffmann: `${SYNTHETIC_AVATAR_BASE_URL}/elena-hoffmann.png`,
  jonasWeber: SYNTHETIC_CONTACT_AVATAR_URLS[6],
  leonBecker: SYNTHETIC_CONTACT_AVATAR_URLS[0],
  marcoSilva: `${SYNTHETIC_AVATAR_BASE_URL}/marco-silva.png`,
  maxBergmann: `${SYNTHETIC_AVATAR_BASE_URL}/max-bergmann.png`,
  rashidMalik: SYNTHETIC_CONTACT_AVATAR_URLS[26],
  sofiaRossi: `${SYNTHETIC_AVATAR_BASE_URL}/sofia-rossi.png`,
  sophieWagner: SYNTHETIC_CONTACT_AVATAR_URLS[19],
  yasminFarouk: SYNTHETIC_CONTACT_AVATAR_URLS[23],
} as const;
