import {
  AlarmClock,
  Award,
  Banknote,
  Barcode,
  BookOpen,
  Box,
  Boxes,
  Briefcase,
  Bug,
  Building2,
  Calendar,
  CalendarCheck,
  Camera,
  Car,
  ChartColumn,
  CheckCircle2,
  ClipboardList,
  Clock,
  Coins,
  Contact,
  CreditCard,
  Database,
  Factory,
  FileText,
  Files,
  Filter,
  Flag,
  Folder,
  Gavel,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HardDrive,
  Headset,
  Heart,
  Hotel,
  House,
  IdCard,
  Inbox,
  Key,
  Landmark,
  Laptop,
  Layers,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageSquare,
  Milestone,
  Music,
  Network,
  Newspaper,
  Notebook,
  Package,
  Palette,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Receipt,
  Repeat,
  Rocket,
  Scale,
  ScrollText,
  Server,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Signature,
  Smartphone,
  SquareKanban,
  Stamp,
  Star,
  Stethoscope,
  Store,
  Tag,
  Target,
  Ticket,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  User,
  UserCheck,
  UserPlus,
  Users,
  UsersRound,
  Utensils,
  Wallet,
  Warehouse,
  Wrench,
  Handshake,
} from "lucide-react";

const icons = {
  contact: Users,
  user: User,
  usersRound: UsersRound,
  userCheck: UserCheck,
  userPlus: UserPlus,
  contactCard: Contact,
  idCard: IdCard,
  graduationCap: GraduationCap,
  building: Building2,
  factory: Factory,
  store: Store,
  landmark: Landmark,
  warehouse: Warehouse,
  network: Network,
  handshake: TrendingUp,
  deal: Handshake,
  target: Target,
  trophy: Trophy,
  filter: Filter,
  chart: ChartColumn,
  megaphone: Megaphone,
  coins: Coins,
  banknote: Banknote,
  creditCard: CreditCard,
  wallet: Wallet,
  receipt: Receipt,
  piggyBank: PiggyBank,
  percent: Percent,
  package: Package,
  box: Box,
  boxes: Boxes,
  tag: Tag,
  cart: ShoppingCart,
  bag: ShoppingBag,
  barcode: Barcode,
  briefcase: Briefcase,
  kanban: SquareKanban,
  rocket: Rocket,
  flag: Flag,
  milestone: Milestone,
  layers: Layers,
  clipboard: ClipboardList,
  repeat: Repeat,
  check: CheckCircle2,
  ticket: Ticket,
  lifeBuoy: LifeBuoy,
  bug: Bug,
  message: MessageSquare,
  headset: Headset,
  inbox: Inbox,
  alert: TriangleAlert,
  document: FileText,
  files: Files,
  folder: Folder,
  signature: Signature,
  book: BookOpen,
  notebook: Notebook,
  newspaper: Newspaper,
  list: List,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  clock: Clock,
  alarm: AlarmClock,
  mapPin: MapPin,
  map: Map,
  globe: Globe,
  home: House,
  hotel: Hotel,
  truck: Truck,
  plane: Plane,
  laptop: Laptop,
  smartphone: Smartphone,
  server: Server,
  hardDrive: HardDrive,
  database: Database,
  car: Car,
  wrench: Wrench,
  hammer: Hammer,
  key: Key,
  contract: ScrollText,
  stamp: Stamp,
  shield: ShieldCheck,
  scale: Scale,
  gavel: Gavel,
  star: Star,
  heart: Heart,
  award: Award,
  gift: Gift,
  lightbulb: Lightbulb,
  mail: Mail,
  phone: Phone,
  link: Link,
  palette: Palette,
  camera: Camera,
  music: Music,
  utensils: Utensils,
  stethoscope: Stethoscope,
  pill: Pill,
  leaf: Leaf,
};

export type RecordTypeIconKey = keyof typeof icons;

export const RECORD_TYPE_ICON_KEYS = Object.keys(icons) as RecordTypeIconKey[];

export function recordTypeIcon(icon: string) {
  return Object.hasOwn(icons, icon) ? icons[icon as RecordTypeIconKey] : Folder;
}
