export enum FilterFieldKey {
  userIds = "userIds",
  serviceIds = "serviceIds",
  dealIds = "dealIds",
  organizationIds = "organizationIds",
  contactIds = "contactIds",
  participantContactId = "participantContactId",
  participants = "participants",
  timelineKind = "timelineKind",
  timelineThreadId = "timelineThreadId",
  taskIds = "taskIds",
  updatedAt = "updatedAt",
  createdAt = "createdAt",
  event = "event",
  status = "status",
  provider = "provider",
  state = "state",
}
