import type { $ZodRawIssue } from "zod/v4/core";

export enum CustomErrorCode {
  apiKeyMaxExpiration = "apiKeyMaxExpiration",
  assigneeRequired = "assigneeRequired",
  emailMismatch = "emailMismatch",
  passwordMismatch = "passwordMismatch",
  passwordInvalid = "passwordInvalid",
  emailNotVerified = "emailNotVerified",
  invalidCredentials = "invalidCredentials",
  emailAlreadyExists = "emailAlreadyExists",
  termsNotAgreed = "termsNotAgreed",
  customColumnNotFound = "customColumnNotFound",
  invalidChannelValue = "invalidChannelValue",
  channelAlreadyLinked = "channelAlreadyLinked",
  customFieldInvalidEmail = "customFieldInvalidEmail",
  customFieldInvalidPhone = "customFieldInvalidPhone",
  customFieldInvalidUrl = "customFieldInvalidUrl",
  urlInvalidProtocol = "urlInvalidProtocol",
  customFieldInvalidCurrency = "customFieldInvalidCurrency",
  customFieldInvalidDate = "customFieldInvalidDate",
  customFieldInvalidDateTime = "customFieldInvalidDateTime",
  customFieldInvalidDateRange = "customFieldInvalidDateRange",
  customFieldInvalidDateTimeRange = "customFieldInvalidDateTimeRange",
  customFieldInvalidSingleSelect = "customFieldInvalidSingleSelect",
  widgetGroupByCustomColumnIdRequired = "widgetGroupByCustomColumnIdRequired",
  widgetDealQuantityOnlyForService = "widgetDealQuantityOnlyForService",
  widgetGroupByEntityTypeNotAllowedForCount = "widgetGroupByEntityTypeNotAllowedForCount",
  widgetGroupByTypeMustMatchEntityType = "widgetGroupByTypeMustMatchEntityType",
  widgetDealFiltersNotAllowedForDealEntityType = "widgetDealFiltersNotAllowedForDealEntityType",
  widgetDealAggregationNotAllowedForTask = "widgetDealAggregationNotAllowedForTask",
  widgetTaskCanOnlyGroupByCustomColumn = "widgetTaskCanOnlyGroupByCustomColumn",
  taskOnlyCustomTasksCanBeDeleted = "taskOnlyCustomTasksCanBeDeleted",
  taskNameCannotBeChangedForSystemTasks = "taskNameCannotBeChangedForSystemTasks",
  organizationNotFound = "organizationNotFound",
  userNotFound = "userNotFound",
  dealNotFound = "dealNotFound",
  serviceNotFound = "serviceNotFound",
  contactNotFound = "contactNotFound",
  taskNotFound = "taskNotFound",
  invalidFilterField = "invalidFilterField",
  invalidFilterValue = "invalidFilterValue",
  invalidSortField = "invalidSortField",
  filterBetweenInvalidArrayLength = "filterBetweenInvalidArrayLength",
  notesInvalidFormat = "notesInvalidFormat",
  notesExceedsMaxLength = "notesExceedsMaxLength",
  sendEmailTargetRequired = "sendEmailTargetRequired",
  unipileResourceNotFound = "unipileResourceNotFound",
  unipileProviderError = "unipileProviderError",
  unipileServiceUnavailable = "unipileServiceUnavailable",
  unipileRequestTimeout = "unipileRequestTimeout",
  unipileDisconnectedAccount = "unipileDisconnectedAccount",
  unipileUnknown = "unipileUnknown",
  generic = "generic",
}

export type ZodLocaleModule = {
  default: () => {
    localeError: (issue: $ZodRawIssue) => string;
  };
};
