export const WIKI_SYNTHESIS_GROUNDING_INSTRUCTION = [
  "Ground every factual claim and example in one of that page's cited, freshly returned source passages. Supply sections.evidence with the exact sourceId and unmodified supporting quotations for every section; never reuse an unrelated quotation to satisfy validation. Check a compact working brief pairing each claim or example with its supporting passage; keep this brief and evidence quotations out of authored content and the final answer.",
  "Preserve approximate numbers, conditions, exceptions, attribution and whether a case is ongoing, proposed or completed. Do not infer technical inputs, integrations, APIs, customer roles or departments, results, guarantees or internal rules from an offering name, industry knowledge or sensible practice.",
  "Evidence elsewhere in the crawl does not justify an uncited claim. Reread and include that source in this page's sourceIds, or omit the claim. If four cited sources cannot support the whole scope, narrow the page rather than substitute an unrelated source.",
  "Examples must come from cited text. Translate every ordinary source-language example into the Knowledge Base language, label translated examples as translations, and do not present a translation as a verbatim quotation. Do not retain original-language phrases in parentheses or terminology lists. Only proper names and technical identifiers retain their original spelling; raw source quotations belong exclusively in sections.evidence.",
  "A narrower paraphrase is safer than a broader claim. Supporting an ongoing implementation does not mean delivering a completed project; reducing a dependency or risk does not mean eliminating it; several people does not mean one person; testing does not imply automated or continuous testing. Preserve the source's exact scope and status rather than filling in familiar industry practices.",
  "Give the Operating Guide actual saved page names and links without factual product summaries that require additional citations. Public contacts and director titles do not establish internal commercial approval authority. Unknown approval, qualification and handover rules belong only in gaps; clearly label any proposed communication guidance as a recommendation.",
  "Separate observed facts from explicitly labelled writing or sales recommendations; a recommendation is not an approved company policy. Unknowns become neutral questions without assuming an architecture, customer outcome, approval rule or policy. Check every claim and example against its supporting passage before creating; omit unsupported assertions.",
].join(" ");
