export const WIKI_SYNTHESIS_GROUNDING_INSTRUCTION = [
  "Choose supporting evidence before composing content. For each intended claim, first select a complete, exact source sentence or contiguous passage; identify its attribution, scope, conditions and limitations; then write one conservative paraphrase that keeps them. If no passage supports the entire claim, narrow or omit it. Every factual claim and example needs its own support from that page's cited, freshly returned sources; unrelated evidence cannot justify additional claims. Keep private evidence quotations out of authored content and the final answer.",
  "Report security, compliance, savings, accuracy and customer outcomes as attributed public source claims, not independently verified assurances. Keep the original possibility, degree of risk reduction, conditions, exceptions, approximate figures and whether work is ongoing, proposed or completed. A source saying a method may reduce a risk must remain an attributed, conditional risk-reduction statement. Known limitations belong beside the related capability, not only in gaps. A passage describing a threat does not prove the product implements a countermeasure. Do not infer technical inputs, integrations, APIs, customer roles or departments, storage design, guarantees or internal rules from general industry practice.",
  "Evidence elsewhere in the crawl does not justify an uncited claim. Reread and include that source in this page's sourceIds, or omit the claim. If four cited sources cannot support the whole scope, narrow the page rather than substitute an unrelated source.",
  "Examples must come from cited text. Translate every ordinary source-language example into the Knowledge Base language, label translated examples as translations, and do not present a translation as a verbatim quotation. Do not retain original-language phrases in parentheses or terminology lists. Only proper names and technical identifiers retain their original spelling; raw source quotations belong exclusively in sections.evidence.",
  "A narrower paraphrase is safer than a broader claim. Supporting an ongoing implementation does not mean delivering a completed project; reducing a dependency or risk does not mean eliminating it; several people does not mean one person; testing does not imply automated or continuous testing. Preserve the source's exact scope and status rather than filling in familiar industry practices.",
  "Give the Operating Guide actual saved page names and links without factual product summaries that require additional citations. Public contacts and director titles do not establish internal commercial approval authority. Unknown approval, qualification and handover rules belong only in gaps; clearly label any proposed communication guidance as a recommendation.",
  "Separate observed facts from explicitly labelled writing or sales recommendations; a recommendation is not an approved company policy. Unknowns become neutral questions without assuming an architecture, customer outcome, approval rule or policy. Check every claim and example against its supporting passage before creating; omit unsupported assertions.",
].join(" ");
