export const LEGACY_CRM_TABLES = [
  "Contact",
  "Organization",
  "Deal",
  "Service",
  "Task",
  "CustomColumn",
  "CustomFieldValue",
  "ContactIdentifier",
  "ServiceDeal",
  "ServiceUser",
  "DealOrganization",
  "DealUser",
  "DealContact",
  "ContactUser",
  "OrganizationUser",
  "TaskUser",
  "TaskContact",
  "TaskOrganization",
  "TaskDeal",
  "TaskService",
  "ContactOrganization",
  "EntityTerminology",
] as const;
