export const RETRIEVAL_TYPO_PREFIX = 3;
export const RETRIEVAL_TYPO_LENGTH_SLACK = 2;
export const RETRIEVAL_TYPO_MIN_SIMILARITY = 0.4;
export const RETRIEVAL_TYPO_TRANSPOSITION_MIN_LENGTH = 5;
export const RETRIEVAL_TYPO_DOCUMENT_LIMIT = 200;
